import { useState } from "react";
import DateTimePicker, { type DateTimePickerEvent } from "@react-native-community/datetimepicker";
import { Alert, Platform, Pressable, StyleSheet, Text, View } from "react-native";
import { CalendarDays, Repeat, Save, Trash2 } from "lucide-react-native";
import { AppButton } from "@/components/ui/AppButton";
import { BottomSheet } from "@/components/ui/BottomSheet";
import { NumberField } from "@/components/ui/NumberField";
import { SegmentedControl } from "@/components/ui/SegmentedControl";
import { TextField } from "@/components/ui/TextField";
import { warning } from "@/lib/haptics";
import { describeRecurrence, todayYmd } from "@/lib/money/recurrence";
import { useMoneyStore } from "@/lib/money/store";
import type { RecurrenceFrequency, Transaction, TxKind } from "@/lib/money/types";
import { formatCurrency } from "@/lib/utils";
import { useTheme } from "@/theme/ThemeProvider";
import { PickerSheetRow } from "./PickerSheetRow";

export interface TxForm {
  date: string;
  kind: TxKind;
  amount: number;
  categoryId: string;
  accountId: string;
  note: string;
  description: string;
  recurring: boolean;
  frequency: RecurrenceFrequency;
  interval: number;
  endDate: string;
}

export function defaultTransactionForm(store: ReturnType<typeof useMoneyStore.getState>, kind: TxKind): TxForm {
  return { date: todayYmd(), kind, amount: 0, categoryId: firstCategory(store, kind), accountId: store.accounts[0]?.id ?? "acct-cash", note: "", description: "", recurring: false, frequency: "monthly", interval: 1, endDate: "" };
}

export function firstCategory(store: ReturnType<typeof useMoneyStore.getState>, kind: TxKind) {
  return store.categories.find((category) => category.kind === kind)?.id ?? store.categories[0]?.id ?? "";
}

export function AddTransactionSheet({
  open,
  editing,
  form,
  setForm,
  onClose,
  onSave
}: {
  open: boolean;
  editing: Transaction | null;
  form: TxForm;
  setForm: (updater: (current: TxForm) => TxForm) => void;
  onClose: () => void;
  onSave: () => void;
}) {
  const { colors } = useTheme();
  const styles = makeStyles(colors);
  const store = useMoneyStore();
  const [datePickerOpen, setDatePickerOpen] = useState(false);
  const [endDatePickerOpen, setEndDatePickerOpen] = useState(false);

  const linkedRule = editing?.recurrenceId
    ? store.recurrenceRules.find((rule) => rule.id === editing.recurrenceId)
    : null;

  const remove = () => {
    if (!editing) return;
    const label = editing.description || editing.note || formatCurrency(editing.amount);
    if (linkedRule) {
      Alert.alert(
        "Delete recurring transaction",
        "This transaction was created by a recurring rule. Delete just this occurrence, or stop the rule entirely?",
        [
          { text: "Cancel", style: "cancel" },
          {
            text: "Only this",
            onPress: () => { warning(); store.deleteTransaction(editing.id); onClose(); }
          },
          {
            text: "Stop rule",
            style: "destructive",
            onPress: () => { warning(); store.deleteRecurrenceRule(linkedRule.id, false); store.deleteTransaction(editing.id); onClose(); }
          }
        ]
      );
      return;
    }
    Alert.alert("Delete transaction?", label, [
      { text: "Cancel" },
      { text: "Delete", style: "destructive", onPress: () => { warning(); store.deleteTransaction(editing.id); onClose(); } }
    ]);
  };

  return (
    <BottomSheet open={open} onClose={onClose}>
      <Text style={styles.sheetTitle}>{editing ? "Edit" : "Add"} transaction</Text>
      <SegmentedControl
        value={form.kind}
        options={[{ label: "Expense", value: "expense" }, { label: "Income", value: "income" }]}
        onChange={(kind) => setForm((current) => ({ ...current, kind, categoryId: firstCategory(store, kind) }))}
        disabled={!!editing}
      />
      {linkedRule ? (
        <View style={styles.linkedRule}>
          <Repeat size={14} color={colors.primary} />
          <Text style={styles.linkedRuleText}>Generated by recurring rule — {describeRecurrence(linkedRule)}</Text>
        </View>
      ) : null}
      <NumberField label="Amount" value={form.amount} onChange={(amount) => setForm((current) => ({ ...current, amount }))} prefix="$" format="currency" />
      <Pressable onPress={() => setDatePickerOpen(true)} style={styles.pickerRow}>
        <View style={styles.pickerIcon}><CalendarDays size={16} color={colors.primary} /></View>
        <View style={{ flex: 1 }}>
          <Text style={styles.pickerLabel}>Date</Text>
          <Text style={styles.pickerValue}>{form.date || todayYmd()}</Text>
        </View>
      </Pressable>
      {datePickerOpen ? (
        <View style={styles.datePickerWrap}>
          <DateTimePicker
            value={parseYmd(form.date)}
            mode="date"
            display={Platform.OS === "ios" ? "spinner" : "default"}
            onChange={(event, date) => handleDateChange(event, date, (nextDate) => setForm((current) => ({ ...current, date: nextDate })), setDatePickerOpen)}
          />
          {Platform.OS === "ios" ? <Pressable onPress={() => setDatePickerOpen(false)} style={styles.doneButton}><Text style={styles.doneText}>Done</Text></Pressable> : null}
        </View>
      ) : null}
      <PickerSheetRow label="Category" value={form.categoryId} options={store.categories.filter((category) => category.kind === form.kind).map((category) => ({ label: category.label, value: category.id }))} onChange={(categoryId) => setForm((current) => ({ ...current, categoryId }))} />
      <PickerSheetRow label="Account" value={form.accountId} options={store.accounts.map((account) => ({ label: account.name, value: account.id }))} onChange={(accountId) => setForm((current) => ({ ...current, accountId }))} />
      <TextField label="Description" value={form.description} onChange={(description) => setForm((current) => ({ ...current, description }))} />
      <TextField label="Note" value={form.note} onChange={(note) => setForm((current) => ({ ...current, note }))} />
      {!editing ? (
        <Pressable onPress={() => setForm((current) => ({ ...current, recurring: !current.recurring }))}>
          <Text style={styles.link}>{form.recurring ? "Recurring enabled" : "Make recurring"}</Text>
        </Pressable>
      ) : null}
      {form.recurring && !editing ? (
        <>
          <View style={styles.row}>
            <View style={{ flex: 1 }}>
              <PickerSheetRow
                label="Frequency"
                value={form.frequency}
                options={[
                  { label: "Daily", value: "daily" },
                  { label: "Weekly", value: "weekly" },
                  { label: "Monthly", value: "monthly" },
                  { label: "Yearly", value: "yearly" }
                ]}
                onChange={(frequency) => setForm((current) => ({ ...current, frequency }))}
              />
            </View>
            <View style={{ flex: 1 }}>
              <NumberField label="Interval" value={form.interval} onChange={(interval) => setForm((current) => ({ ...current, interval }))} min={1} />
            </View>
          </View>
          <Pressable onPress={() => setEndDatePickerOpen(true)} style={styles.pickerRow}>
            <View style={styles.pickerIcon}><CalendarDays size={16} color={colors.primary} /></View>
            <View style={{ flex: 1 }}>
              <Text style={styles.pickerLabel}>End date (optional)</Text>
              <Text style={styles.pickerValue}>{form.endDate || "No end"}</Text>
            </View>
            {form.endDate ? (
              <Pressable onPress={() => setForm((current) => ({ ...current, endDate: "" }))} hitSlop={8}>
                <Text style={styles.clearText}>Clear</Text>
              </Pressable>
            ) : null}
          </Pressable>
          {endDatePickerOpen ? (
            <View style={styles.datePickerWrap}>
              <DateTimePicker
                value={form.endDate ? parseYmd(form.endDate) : parseYmd(form.date)}
                mode="date"
                display={Platform.OS === "ios" ? "spinner" : "default"}
                onChange={(event, date) => handleDateChange(event, date, (nextDate) => setForm((current) => ({ ...current, endDate: nextDate })), setEndDatePickerOpen)}
              />
              {Platform.OS === "ios" ? <Pressable onPress={() => setEndDatePickerOpen(false)} style={styles.doneButton}><Text style={styles.doneText}>Done</Text></Pressable> : null}
            </View>
          ) : null}
        </>
      ) : null}
      <View style={styles.row}>
        {editing ? <AppButton label="Delete" variant="destructive" onPress={remove} icon={<Trash2 size={16} color={colors.primaryForeground} />} /> : null}
        <AppButton label="Save" onPress={onSave} icon={<Save size={16} color={colors.primaryForeground} />} />
      </View>
    </BottomSheet>
  );
}

function handleDateChange(event: DateTimePickerEvent, date: Date | undefined, onPick: (date: string) => void, setOpen: (open: boolean) => void) {
  if (Platform.OS !== "ios") setOpen(false);
  if (event.type === "dismissed" || !date) return;
  onPick(formatYmd(date));
}

function parseYmd(value: string) {
  const [year, month, day] = value.split("-").map(Number);
  const fallback = new Date();
  if (!year || !month || !day) return fallback;
  return new Date(year, month - 1, day);
}

function formatYmd(date: Date) {
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
}

const makeStyles = (colors: ReturnType<typeof useTheme>["colors"]) => StyleSheet.create({
  clearText: { color: colors.mutedForeground, fontWeight: "800", fontSize: 12 },
  datePickerWrap: { borderRadius: 14, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.card, overflow: "hidden" },
  doneButton: { minHeight: 42, alignItems: "center", justifyContent: "center", borderTopWidth: 1, borderTopColor: colors.border },
  doneText: { color: colors.primary, fontWeight: "900" },
  link: { color: colors.primary, fontWeight: "900" },
  linkedRule: { flexDirection: "row", alignItems: "center", gap: 8, borderWidth: 1, borderColor: colors.primary, backgroundColor: colors.primaryWash, borderRadius: 12, paddingHorizontal: 12, paddingVertical: 10 },
  linkedRuleText: { color: colors.mutedForeground, fontSize: 12, fontWeight: "700", flex: 1 },
  pickerIcon: { width: 34, height: 34, borderRadius: 17, backgroundColor: colors.primaryWash, alignItems: "center", justifyContent: "center" },
  pickerLabel: { color: colors.mutedForeground, fontSize: 12, fontWeight: "800" },
  pickerRow: { minHeight: 54, borderWidth: 1, borderColor: colors.border, borderRadius: 14, backgroundColor: colors.card, paddingHorizontal: 12, paddingVertical: 8, flexDirection: "row", alignItems: "center", gap: 10 },
  pickerValue: { color: colors.foreground, fontSize: 15, fontWeight: "900", marginTop: 2 },
  row: { flexDirection: "row", gap: 12, marginVertical: 10 },
  sheetTitle: { color: colors.foreground, fontSize: 18, fontWeight: "900" }
});
