import AsyncStorage from "@react-native-async-storage/async-storage";
import { create } from "zustand";
import { createJSONStorage, persist } from "zustand/middleware";
import type { SavingsCategory, MonthlyEntry } from "./types";
import { trackerApi } from "@/lib/api/tracker";
export const DEFAULT_CATEGORIES:SavingsCategory[]=[{id:"stocks",label:"Stocks / Equity",color:"#00b3b5"},{id:"sip",label:"SIP / Mutual Funds",color:"#00bdca"},{id:"401k",label:"401k / EPF",color:"#00af44"},{id:"gold",label:"Gold",color:"#eaa01a"},{id:"savings",label:"Savings / HYSA",color:"#3bacda"}];
const isLocalId = (id: string) => !/^[0-9a-f]{8}-[0-9a-f]{4}/i.test(id);
interface TrackerStore{syncUserId:string|null;syncing:boolean;categories:SavingsCategory[];entries:MonthlyEntry[];upsertEntry:(e:MonthlyEntry)=>void;addCategory:(c:SavingsCategory)=>void;removeCategory:(id:string)=>void;getEntry:(m:string,c:string)=>MonthlyEntry|undefined;initSync:(userId:string)=>Promise<void>;disconnectSync:()=>void;reset:()=>void;}
export const useTrackerStore=create<TrackerStore>()(persist((set,get)=>({syncUserId:null,syncing:false,categories:DEFAULT_CATEGORIES,entries:[],upsertEntry:(entry)=>{set(s=>{const i=s.entries.findIndex(e=>e.month===entry.month&&e.categoryId===entry.categoryId);const entries=[...s.entries];if(i>=0)entries[i]=entry;else entries.push(entry);return{entries}});if(get().syncUserId&&!isLocalId(entry.categoryId))trackerApi.upsertEntries([entry]).catch(()=>{});},addCategory:(cat)=>{set(s=>({categories:[...s.categories,cat]}));if(get().syncUserId)trackerApi.createCategory(cat.label,cat.color).then(server=>set(s=>({categories:s.categories.map(c=>c.id===cat.id?{id:server.id,label:server.label,color:server.color}:c)}))).catch(()=>{});},removeCategory:(id)=>{set(s=>({categories:s.categories.filter(c=>c.id!==id),entries:s.entries.filter(e=>e.categoryId!==id)}));if(get().syncUserId&&!isLocalId(id))trackerApi.deleteCategory(id).catch(()=>{});},getEntry:(m,c)=>get().entries.find(e=>e.month===m&&e.categoryId===c),initSync:async(userId)=>{if(get().syncUserId===userId)return;set({syncing:true});try{const [serverCategories,serverEntries]=await Promise.all([trackerApi.getCategories(),trackerApi.getEntries()]);if(serverCategories.length||serverEntries.length){set({syncUserId:userId,categories:serverCategories.map(c=>({id:c.id,label:c.label,color:c.color})),entries:serverEntries.map(e=>({month:e.month,categoryId:e.category_id,planned:Number(e.planned??0),actual:Number(e.actual??0)}))});return;}const local=get();set({syncUserId:userId});const localCats=local.categories.filter(c=>isLocalId(c.id));for(const cat of localCats){await trackerApi.createCategory(cat.label,cat.color);}if(local.entries.length)await trackerApi.upsertEntries(local.entries.filter(e=>!isLocalId(e.categoryId)));}finally{set({syncing:false});}},disconnectSync:()=>set({syncUserId:null}),reset:()=>set({syncUserId:null,syncing:false,categories:DEFAULT_CATEGORIES,entries:[]})}),{name:"fire-tracker",storage:createJSONStorage(()=>AsyncStorage),partialize:({categories,entries})=>({categories,entries})}));
